apiVersion: v1
kind: Pod
metadata:
  name: fortune-emptydir
spec:
  volumes:
    - name: content
      emptyDir: {}
  containers:
    - name: nginx
      image: nginx:alpine
      volumeMounts:
        - name: content
          mountPath: /usr/share/nginx/html
      lifecycle:
        postStart:
          exec:
            command:
              - sh
              - -c
              - "ls /usr/share/nginx/html/quote || (apk add fortune && fortune > /usr/share/nginx/html/quote)"
      ports:
        - name: http
          containerPort: 80
