apiVersion: v1
kind: Pod
metadata:
  name: fortune-no-volume
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      lifecycle:
        postStart:
          exec:
            command:
              - sh
              - -c
              - "ls /usr/share/nginx/html/quote || (apk add fortune && fortune > /usr/share/nginx/html/quote)"
      ports:
        - name: http
          containerPort: 80
