apiVersion: v1
kind: Pod
metadata:
  name: poststart-httpget
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      lifecycle:
        postStart:
          httpGet:
            port: 80
            path: /warmup
      ports:
        - name: http
          containerPort: 80
