apiVersion: v1
kind: Pod
metadata:
  name: poststart-httpget-slow
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      command:
        - sh
        - -c
        - "sleep 1; nginx"
      lifecycle:
        postStart:
          httpGet:
            port: 80
            path: /warmup
      ports:
        - name: http
          containerPort: 80
